app:
  name: bff
  image:
    repository: "onecx/onecx-document-bff"
  operator:
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          document:
            read: permission on all GET requests and POST search
            write: permission on PUT, POST, PATCH requests, where objects are saved or updated
            delete: permission on all DELETE requests
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-doc:all,ocx-fs:read, ocx-fs:write, ocx-fs:delete, ocx-pm:read ]
    microservice:
      spec:
        description: OneCX Document Backend For Frontend
        name: OneCX Document BFF